default_config:

# person:

# system_health:

# history:

# updater:

# mobile_app:

# map:

# sun:

# config:

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: !secret http_base_url
  ip_ban_enabled: true
  cors_allowed_origins:
    - "http://localhost:4200"

api:

websocket_api:

ffmpeg:

# Sensors
sensor: !include sensor.yaml

binary_sensor:
  - platform: mqtt
    name: "Garage Motion"
    state_topic: "cameras/UpstairsMotion/motion"
    device_class: motion
  - platform: workday
    country: AU
    province: VIC

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key
    
dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: AU
  devices:
    - device_id: SZ1-AU-JJA1044A
      device_ip: 192.168.10.75

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120

media_player:
  - platform: braviatv
    host: 192.168.10.72
    name: "Sony Bravia TV 60 inch"
  - platform: kodi
    host: 192.168.10.70
    
notify:
  - platform: kodi
    name: KODI_NOTIFIER
    host: 192.168.10.70
  - platform: html5
    name: GOOGLE_NOTIFIER
    vapid_pub_key: !secret google_vapid_pub_key
    vapid_prv_key: !secret google_vapid_prv_key
    vapid_email: !secret google_vapid_email
    
weather:
  - platform: bom
    name: Essendon Airport
    station: IDV60901.95866
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
      
camera:
  - platform: bom
    location: Melbourne
  - platform: mjpeg
    name: UpstairsCamera
    mjpeg_url: http://192.168.10.74:8081/
    verify_ssl: false
  - platform: aarlo
    
stream:

airvisual:
  api_key: !secret airvisual_token
  geographies:
    city: maribyrnong
    state: victoria
    country: australia

# input_boolean:
#   oliver_heater:
#     name: Switch Climate Managment On
#     # initial: off

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state