---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none
  # reboot_timeout: ${reboot_timeout}
  ap:
    ssid: ${device}
    password: !secret ap_wifi_password
captive_portal: