---
substitutions:
  device: arlec_switch_board_1
  name: Arlec Switch 1
  reboot_timeout: 7d
  update_interval: 60s

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml  

<<: !include device_config/arlec_switch_board.yaml