---
substitutions:
  device: kogan_3
  name: Kogan 3
  reboot_timeout: 7d
  update_interval: 60s

esphome:
  name: ${device}
  platform: ESP8266
  board: esp8285

<<: !include common/common.yaml

<<: !include device_config/kogan_plug_with_energy.yaml

# binary_sensor:
#   - platform: gpio
#     pin:
#       number: GPIO0
#       mode: INPUT_PULLUP
#       inverted: true
#     name: "$name Power Button"
#     on_press:
#       - switch.toggle: relay

#   - platform: status
#     name: "$name Status"

# switch:
#   - platform: gpio
#     id: green_led
#     pin:
#       number: GPIO13
#       inverted: true
#     restore_mode: ALWAYS_OFF

#   - platform: gpio
#     name: "$name"
#     pin: GPIO14
#     id: relay
#     icon: mdi:television
#     restore_mode: ALWAYS_OFF
    
# sensor:
#   - !include common/sensor/wifi-signal.yaml
#   - !include common/sensor/uptime.yaml  
#   - platform: hlw8012
#     sel_pin:
#       number: GPIO12
#       inverted: true
#     cf_pin: GPIO04
#     cf1_pin: GPIO05
#     current:
#       name: "$name Current"
#       unit_of_measurement: A
#     voltage:
#       name: "$name Voltage"
#       unit_of_measurement: V
#     power:
#       id: kogan_plug_1_wattage
#       name: "$name Power"
#       unit_of_measurement: W
#     current_resistor: "0.00087"   ### HIGHER VALUE GIVES LOWER WATTAGE
#     voltage_divider: "2030"   ### LOWER VALUE GIVES LOWER VOLTAGE
#     change_mode_every: 8
#     update_interval: 5s

#   - platform: total_daily_energy
#     name: "$name Daily Energy"
#     power_id: kogan_plug_1_wattage
#     filters:
#       - multiply: 0.001
#     unit_of_measurement: kWh

# time:
#   - platform: homeassistant
#     id: homeassistant_time