---
substitutions:
  device: sonoff_basic_1
  name: Sonoff Basic 1
  reboot_timeout: 7d
  update_interval: 60s
  
esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml  

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "$name Switch"
    on_press:
      - switch.toggle: relay
    
switch:
  - platform: gpio
    name: "$name relay"
    pin: GPIO12
    id: relay
    restore_mode: restore_default_off